version: 2

project_name: tahuna

builds:
  - id: tahuna
    dir: cli
    main: .
    binary: tahuna
    ldflags:
      - -s -w -X main.cliVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64

archives:
  - id: tahuna
    ids:
      - tahuna
    formats: [tar.gz]
    name_template: "tahuna_{{ .Os }}_{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: Pazuzzu
    name: tahuna-cli
  target_commitish: main
  replace_existing_artifacts: true
  mode: replace
  draft: false
  prerelease: auto
