.PHONY: web backend worker cli build test fmt dev tree

web:
	$(MAKE) -C .. web

backend:
	$(MAKE) -C .. backend

worker:
	$(MAKE) -C .. worker

cli:
	$(MAKE) -C .. cli

build:
	$(MAKE) -C .. build

test:
	$(MAKE) -C .. test

fmt:
	$(MAKE) -C .. fmt

dev:
	$(MAKE) -C .. dev

tree:
	$(MAKE) -C .. tree
