.PHONY: \
	install run \
	install-web install-backend install-worker install-provisioner install-cli \
	run-web run-backend run-worker run-provisioner run-cli \
	web backend worker provisioner cli \
	build test fmt dev tree

install:
	$(MAKE) -C .. install

run:
	$(MAKE) -C .. run

install-web:
	$(MAKE) -C .. install-web

install-backend:
	$(MAKE) -C .. install-backend

install-worker:
	$(MAKE) -C .. install-worker

install-provisioner:
	$(MAKE) -C .. install-provisioner

install-cli:
	$(MAKE) -C .. install-cli

run-web:
	$(MAKE) -C .. run-web

run-backend:
	$(MAKE) -C .. run-backend

run-worker:
	$(MAKE) -C .. run-worker

run-provisioner:
	$(MAKE) -C .. run-provisioner

run-cli:
	$(MAKE) -C .. run-cli

web:
	$(MAKE) -C .. web

backend:
	$(MAKE) -C .. backend

worker:
	$(MAKE) -C .. worker

provisioner:
	$(MAKE) -C .. provisioner

cli:
	$(MAKE) -C .. cli

build:
	$(MAKE) -C .. build

test:
	$(MAKE) -C .. test

fmt:
	$(MAKE) -C .. fmt

dev:
	$(MAKE) -C .. dev

tree:
	$(MAKE) -C .. tree
