import {
  ACTIVE_SERVE_LIFECYCLE_STATUSES,
  SERVE_LIFECYCLE_STATUS,
  TERMINAL_SERVE_LIFECYCLE_STATUSES,
} from "@convex/core/serveLifecyclePlan"

export const SERVE_STATUS = SERVE_LIFECYCLE_STATUS
export const ACTIVE_SERVE_STATUSES = ACTIVE_SERVE_LIFECYCLE_STATUSES
export const TERMINAL_SERVE_STATUSES = TERMINAL_SERVE_LIFECYCLE_STATUSES
