project: test_ml_project
entrypoint: train.py
command:
  - python
  - train.py
train:
  epochs: 2
  batch_size: 64
  learning_rate: 0.001
  logging_steps: 1
  data_dir: data/mnist
  output_dir: outputs
data:
  path: data
resources:
  gpu_type: NVIDIA GeForce RTX 4090
  gpu_count: 1
  volume_gb: 80
